# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-31 02:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('title', models.CharField(default='No album title', max_length=100)),
                ('image', models.CharField(default='No image', max_length=200)),
                ('albumId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('external', models.CharField(default='No external URL', max_length=100)),
                ('uri', models.CharField(default='No URI', max_length=100)),
                ('mainArtist', models.CharField(default='No artist', max_length=20)),
                ('artists', models.CharField(default='No artists', max_length=20)),
                ('markets', models.CharField(default='No available markets', max_length=100)),
                ('tracks', models.CharField(default='No tracks', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('genres', models.CharField(default='No genres', max_length=100)),
                ('name', models.CharField(default='No name', max_length=100)),
                ('artistId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('external', models.CharField(default='No external URL', max_length=100)),
                ('uri', models.CharField(default='No URI', max_length=100)),
                ('image', models.CharField(default='No image', max_length=100)),
                ('popularity', models.CharField(default='0', max_length=3)),
                ('numOfFollowers', models.CharField(default='0', max_length=20)),
                ('topTenTracks', models.CharField(default='No top tracks', max_length=1000)),
                ('albums', models.CharField(default='No albums', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songId', models.CharField(default='No song', max_length=10)),
                ('albumId', models.CharField(default='No album', max_length=10)),
                ('artistId', models.CharField(default='No artist', max_length=10)),
                ('comment', models.CharField(default='No comment', max_length=500)),
                ('songTitle', models.CharField(default='No song title', max_length=100)),
                ('albumTitle', models.CharField(default='No album title', max_length=100)),
                ('artistTitle', models.CharField(default='No artist title', max_length=100)),
                ('rating', models.FloatField(default=1, max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('title', models.CharField(default='No song title', max_length=100)),
                ('album', models.CharField(default='No album', max_length=100)),
                ('songId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('preview', models.CharField(default='No preview', max_length=100)),
                ('external', models.CharField(default='No external URL', max_length=100)),
                ('uri', models.CharField(default='No URI', max_length=100)),
                ('duration', models.CharField(default='No duration', max_length=10)),
                ('mainArtist', models.CharField(default='No artist', max_length=20)),
                ('artists', models.CharField(default='No artists', max_length=20)),
                ('popularity', models.CharField(default='0', max_length=3)),
                ('markets', models.CharField(default='No available markets', max_length=100)),
            ],
        ),
    ]
