# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-31 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.FloatField(default='No duration', max_length=10),
        ),
    ]
