# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-31 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20171231_0449'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='query',
            field=models.CharField(default='No query', max_length=100),
        ),
    ]
