# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-31 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_song_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='preview',
            field=models.CharField(blank=True, default='None', max_length=100, null=True),
        ),
    ]
