# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-31 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20171231_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='image',
            field=models.CharField(blank=True, default='None', max_length=100, null=True),
        ),
    ]
