# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-31 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_song_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='albumId',
            field=models.CharField(blank=True, default='No album', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='albumTitle',
            field=models.CharField(blank=True, default='No album title', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='artistId',
            field=models.CharField(blank=True, default='No artist', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='artistTitle',
            field=models.CharField(blank=True, default='No artist title', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='songId',
            field=models.CharField(blank=True, default='No song', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='songTitle',
            field=models.CharField(blank=True, default='No song title', max_length=100, null=True),
        ),
    ]
