# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-31 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20171231_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='songArtists',
            field=models.CharField(blank=True, default='No artists', max_length=10, null=True),
        ),
    ]
