# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-02 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_album_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='albumId',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
