# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-02 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_album_releasedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='popularity',
            field=models.FloatField(default=0, max_length=101),
        ),
        migrations.AlterField(
            model_name='song',
            name='popularity',
            field=models.FloatField(default=0, max_length=101),
        ),
    ]
