# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-02 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_song_thetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='albums',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='topTenTracks',
        ),
        migrations.AlterField(
            model_name='artist',
            name='popularity',
            field=models.FloatField(default=0, max_length=101),
        ),
    ]
