# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-02 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0017_song_artistid'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='albumId',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='artist',
            name='songId',
            field=models.CharField(default='None', max_length=30),
        ),
    ]
