# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-03 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0018_auto_20180102_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='artistId',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='albumId',
            field=models.CharField(blank=True, default='None', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='songId',
            field=models.CharField(blank=True, default='None', max_length=30, null=True),
        ),
    ]
