# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-03 03:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0019_auto_20180103_0029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='albumTitle',
        ),
        migrations.RemoveField(
            model_name='review',
            name='artistTitle',
        ),
        migrations.RemoveField(
            model_name='review',
            name='songArtists',
        ),
        migrations.RemoveField(
            model_name='review',
            name='songTitle',
        ),
    ]
