# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-03 04:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0020_auto_20180103_0337'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('albumId', models.CharField(blank=True, default='No album', max_length=10, null=True)),
                ('albumTitle', models.CharField(blank=True, default='No song title', max_length=100, null=True)),
                ('comment', models.CharField(default='No comment', max_length=500)),
                ('albumArtists', models.CharField(blank=True, default='No artists', max_length=10, null=True)),
                ('rating', models.FloatField(default=1, max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArtistReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artistId', models.CharField(blank=True, default='No artist', max_length=10, null=True)),
                ('comment', models.CharField(default='No comment', max_length=500)),
                ('artistName', models.CharField(blank=True, default='No artist', max_length=10, null=True)),
                ('rating', models.FloatField(default=1, max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SongReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songId', models.CharField(blank=True, default='No song', max_length=10, null=True)),
                ('comment', models.CharField(default='No comment', max_length=500)),
                ('songTitle', models.CharField(blank=True, default='No song title', max_length=100, null=True)),
                ('songArtists', models.CharField(blank=True, default='No artists', max_length=10, null=True)),
                ('rating', models.FloatField(default=1, max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
