# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-03 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0021_auto_20180103_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumreview',
            name='time',
            field=models.CharField(default='No date', max_length=15),
        ),
        migrations.AddField(
            model_name='songreview',
            name='time',
            field=models.CharField(default='No date', max_length=15),
        ),
    ]
