# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-03 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0023_artistreview_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumreview',
            name='image',
            field=models.CharField(default='No image', max_length=100),
        ),
        migrations.AddField(
            model_name='artistreview',
            name='image',
            field=models.CharField(default='No image', max_length=100),
        ),
        migrations.AddField(
            model_name='songreview',
            name='image',
            field=models.CharField(default='No image', max_length=100),
        ),
    ]
