# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-03 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0024_auto_20180103_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='songreview',
            name='albumId',
            field=models.CharField(blank=True, default='No album', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='songreview',
            name='albumTitle',
            field=models.CharField(blank=True, default='No album title', max_length=100, null=True),
        ),
    ]
