# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-11 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0025_auto_20180103_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='albumId',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='album',
            name='artistId',
            field=models.CharField(default='None', max_length=500),
        ),
        migrations.AlterField(
            model_name='album',
            name='artists',
            field=models.CharField(default='No artists', max_length=500),
        ),
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.CharField(default='No image', max_length=500),
        ),
        migrations.AlterField(
            model_name='album',
            name='mainArtist',
            field=models.CharField(default='No artist', max_length=600),
        ),
        migrations.AlterField(
            model_name='album',
            name='popularity',
            field=models.FloatField(default=0, max_length=11),
        ),
        migrations.AlterField(
            model_name='albumreview',
            name='albumArtists',
            field=models.CharField(blank=True, default='No artists', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='albumreview',
            name='albumId',
            field=models.CharField(blank=True, default='No album', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='albumreview',
            name='albumTitle',
            field=models.CharField(blank=True, default='No song title', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='albumreview',
            name='image',
            field=models.CharField(default='No image', max_length=500),
        ),
        migrations.AlterField(
            model_name='albumreview',
            name='rating',
            field=models.FloatField(default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='albumreview',
            name='time',
            field=models.CharField(default='No date', max_length=50),
        ),
        migrations.AlterField(
            model_name='artist',
            name='albumId',
            field=models.CharField(blank=True, default='None', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artistId',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='artist',
            name='external',
            field=models.CharField(default='No external URL', max_length=500),
        ),
        migrations.AlterField(
            model_name='artist',
            name='genres',
            field=models.CharField(default='No genres', max_length=500),
        ),
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.CharField(default='No image', max_length=500),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(default='No name', max_length=500),
        ),
        migrations.AlterField(
            model_name='artist',
            name='numOfFollowers',
            field=models.CharField(default='0', max_length=500),
        ),
        migrations.AlterField(
            model_name='artist',
            name='popularity',
            field=models.FloatField(default=0, max_length=501),
        ),
        migrations.AlterField(
            model_name='artist',
            name='songId',
            field=models.CharField(blank=True, default='None', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='uri',
            field=models.CharField(default='No URI', max_length=500),
        ),
        migrations.AlterField(
            model_name='artistreview',
            name='artistId',
            field=models.CharField(blank=True, default='No artist', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='artistreview',
            name='artistName',
            field=models.CharField(blank=True, default='No artist', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='artistreview',
            name='image',
            field=models.CharField(default='No image', max_length=500),
        ),
        migrations.AlterField(
            model_name='artistreview',
            name='rating',
            field=models.FloatField(default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='artistreview',
            name='time',
            field=models.CharField(default='No date', max_length=50),
        ),
        migrations.AlterField(
            model_name='song',
            name='artists',
            field=models.CharField(default='No artists', max_length=100),
        ),
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.CharField(blank=True, default='None', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='mainArtist',
            field=models.CharField(default='No artist', max_length=100),
        ),
        migrations.AlterField(
            model_name='song',
            name='preview',
            field=models.CharField(blank=True, default='None', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='songreview',
            name='albumId',
            field=models.CharField(blank=True, default='No album', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='songreview',
            name='albumTitle',
            field=models.CharField(blank=True, default='No album title', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='songreview',
            name='image',
            field=models.CharField(default='No image', max_length=500),
        ),
        migrations.AlterField(
            model_name='songreview',
            name='rating',
            field=models.FloatField(default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='songreview',
            name='songArtists',
            field=models.CharField(blank=True, default='No artists', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='songreview',
            name='songId',
            field=models.CharField(blank=True, default='No song', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='songreview',
            name='songTitle',
            field=models.CharField(blank=True, default='No song title', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='songreview',
            name='time',
            field=models.CharField(default='No date', max_length=50),
        ),
    ]
